### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by drew5494** [octomagon/davegrohl#10]
Hi there I have a file vault 2 encrypted external hard drive.  All of my pictures are on this drive and I don't know what to do.  I know the length of the password and that is 12 characters.  It was picked from Apples Password Helper under Memorable which means it consists of a word that is 3-5 characters followed by a number that is 1-3  digits then a symbol and then a word, 3-5 characters again.
Here are some examples of keys it generates: 
vet5}explode
roll52;darn
meshy27&pace
long56'coper
envoi0{Praia
calyx20{they

I appreciate your help greatly :)

**Comment by octomagon** [comment]
Hi!
I'm afraid you might be shit out of luck :(  Whole-disk encryption (aka FileVault) would be pretty pointless if it was an easy thing to bypass.  DaveGrohl was intended to crack user passwords on Macs not using FileVault, and even then it's more mental masturbation than a practical solution.  A user password on any operating system not using whole-disk encryption is merely a mild deterrent.  

A Mac with FileVault turned on with a good password is effectively impossible to break into.  (except maybe for the NSA)

Hit me up at octomagon@gmail.com if you wanna talk more.
