### ISSUE TITLE
Use on secondary keychain file? 

### ISSUE THREAD

**Issue by cdatwood** [octomagon/davegrohl#13]
I have a keychain file that I locked myself out of, but backed up separately before I nuked it and started rebuilding. 

Is there a parameter where I can specify the keychain file it should check?

**Comment by octomagon** [comment]
I don't know the down and dirty details on how the keychains are unlocked and DaveGrohl does not know how to read them.  Butt... OS X keychains are usually opened with the user's login password.  That password is stored in a file located at: /var/db/dslocal/nodes/Default/users/yourUsername.plist  which Dave does know how to read.  Like this:

```
sudo ./dave -p /var/db/dslocal/nodes/Default/users/username.plist
```

So if your keychain was linked to a user and you have a backup of that user, then Dave might be able to help you.  That said, OS X uses a pretty modern password encryption and unless you own a big-ass data center or real-estate in "The Cloud", a brute force attack might be slow and impractical.  

I hope this helps!
(This is a feature that should be added)
