### ISSUE TITLE
shadow_hash.cpp hardcoded path

### ISSUE THREAD

**Issue by NickMich** [octomagon/davegrohl#14]
The dumpHashData method in shadow_hash.cpp was left with a hardcoded path to the .plist file. Looks like the string formatting for the user argument was missed

https://github.com/octomagon/davegrohl/blob/master/src/shadow_hash.cpp#L80

**Comment by octomagon** [comment]
D'oh!  Many thanks!!  Working on a quick fix for this now.

**Comment by octomagon** [comment]
I believe this is working now.  I also added basic error checking to that functionality.
