### ISSUE TITLE
Tag your releases

### ISSUE THREAD

**Issue by straxhaber** [octomagon/davegrohl#15]
If you tag your releases, I will try to get this submitted for inclusion in the Homebrew package repository.

**Comment by octomagon** [comment]
Holy shit.   I've been using git for a while now...  How did I miss tags?!!?  Mind blown.  I'll get on this as soon as I find my pants.

**Comment by straxhaber** [comment]
Awesome. When do you think you'll be getting to a stable release? (i.e., something you'd feel comfortable not calling -alpha). That is when I'll submit it for inclusion in homebrew (which might get you a lot more users).
