### ISSUE TITLE
Crack dumped hash

### ISSUE THREAD

**Issue by pomo-mondreganto** [octomagon/davegrohl#16]
Any way to crack saved hash on other machine using your app?

**Comment by octomagon** [comment]
Do you know what format it's saved in?  a user plist? raw hex?
Version 2.1 supports cracking user plists.  You can get that version at davegrohl.org.

This will eventually be added to V3.

**Comment by octomagon** [comment]
Closing this cuz I'm drunk with power... and whiskey.
