### ISSUE TITLE
Getting the error "error: invalid value 'c++14' in '-std=c++14' "

### ISSUE THREAD

**Issue by ghost** [octomagon/davegrohl#18]
The full error is:

clang++ -std=c++14 -stdlib=libc++ -ObjC++ -I include -I mbedtls/include -c -o build/app_controller.o src/app_controller.cpp
error: invalid value 'c++14' in '-std=c++14'
make: **\* [build/app_controller.o] Error 1

What can I do to prevent this from happening?

Alternatively,

My situation is that i'm on a laptop provided by an educational establishment. My user is a managed, mobile user and most of the features of the mac are disabled. I cannot enter single-user mode and whenever I attempt to use sudo, I am prompted for an administrator's password which I do not have.

Does anyone have any suggestions on how I should face this problem?

**Comment by octomagon** [comment]
What version of OS X are you running?  It sounds like it may be a bit old.
You can try opening up the Makefile and replacing "c++14" with "c++1y".  That's apparently what it was called many moons ago.  

Keep in mind, Dave generally needs sudo access to extract a user's password hash.
