### ISSUE TITLE
Getting command not found

### ISSUE THREAD

**Issue by zeldaf** [octomagon/davegrohl#19]
When I enter 'sudo ./dave -u some user' I keep getting 'sudo: ./dave: command not found'. I'm running El Capitan 10.11.4 but nothing seems to work. Any help would be greatly appreciated!

**Comment by octomagon** [comment]
It sounds like the the ‘dave’ executable is not located in your current directory.
Type ‘ls -lh’ and make sure you see ‘dave’ there.
