### ISSUE TITLE
Could not open shadow file.

### ISSUE THREAD

**Issue by tukangsedot** [octomagon/davegrohl#20]
on my macosx 10.11.5 after sudo ./dave -u someuser than "Could not open shadow file "

**Comment by octomagon** [comment]
In "sudo ./dave -u someuser", make sure "someuser" is the short name of your user.  In other words, if you look in /Users, it should exactly match the name of your user's folder.

If it still doesn't work, type this "sudo ls /var/db/dslocal/nodes/Default/users" and make sure there is a .plist file in that folder that matches your value for "someuser".

Generally, if your username is "Boba Fett", the corresponding command would be:
    sudo ./dave -u bobafett

**Comment by nippysaurus** [comment]
For what its worth also make sure you are running `dave` with `sudo`.

**Comment by locktight** [comment]
Thanks guys!  I'll "measure twice, cut once", following your advise the
next time I'm geeking on one of my macs.  Kudos!



[image: Bradly Westfield, BS, DC on about.me]

Bradly Westfield, BS, DC
about.me/lipservice
  <http://about.me/lipservice>
