### ISSUE TITLE
Wrong lenght of Entropy key

### ISSUE THREAD

**Issue by dardo82** [octomagon/davegrohl#26]
`dave -s` gives the full output while only half is needed for example in HashCat format.
See also [here](https://apple.stackexchange.com/questions/220729/what-type-of-hash-are-a-macs-password-stored-in#comment286068_220863) and [here](https://gist.github.com/dardo82/a529db7a191f375ef401adfea7156b6d) for further discussion.

**Comment by octomagon** [comment]
I've just added the `-x` or `--hashcat=USERNAME` to Dave 3.01.  This option will output a Mac user's ShadowHashData specifically formatted for Hashcat.  This only works for the Mac implementation of SALTED-SHA512-PBKDF2.  The `-s` option will remain the same as it was never intended to be used for Hashcat.

Basic usage is:
```bash
MacBook-Pro:~/davegrohl$ sudo ./dave --hashcat=USERNAME > hash.txt
MacBook-Pro:~/davegrohl$ hashcat -m 7100 hash.txt wordlist.txt
```
I just pushed v3.01 to master.

**Comment by dardo82** [comment]
I’ll check it out and let you know! 🤓

**Comment by dardo82** [comment]
Have you updated the README file but not the man page?

**Comment by octomagon** [comment]
That's right.  I'll take care of the man page later today.

**Comment by dardo82** [comment]
I’ve just tried it and it works fine,  thanks!

**Comment by octomagon** [comment]
Thanks for checking!  I'll close this once I get the man page updated.

**Comment by octomagon** [comment]
The man page has been updated.  There's still a bit more cleanup to do, but I'll close this issue for now.
